In [36]:
#Test
print("Hello, worldy!")

Hello, worldy!


## This is the result of the print statement!

In [37]:
list1 = [2,3]
list1

[2, 3]

In [38]:
list1 * 2

[2, 3, 2, 3]

In [39]:
import numpy as np
import pandas as pd

test_array = np.array(list1)
print(test_array)

[2 3]


In [40]:
test_array * 4

array([ 8, 12])

In [41]:
arr3 = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [42]:
arr3.shape

(2, 2, 3)

### arr3 here is what we refer to as a "3D array", it has 3 rows, 2 columns and then 2 "sets" (explaining arr3.shape's output from right to left).

In [44]:
np.arange(1, 99)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
np.sum(arr3)

60

In [49]:
print(1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9)

45


In [53]:
x = pd.Series([10,20,30], index=['a','b','c'])
x

a    10
b    20
c    30
dtype: int64

In [57]:
x.index

Index(['a', 'b', 'c'], dtype='object')

In [59]:
x['a']

10

In [62]:
x[0]

/tmp/ipykernel_12407/3629782281.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x[0]


10

In [67]:
new_x = pd.Series(x, index=['a','b','c', 'd','e'])
print(new_x)
new_x

a    10.0
b    20.0
c    30.0
d     NaN
e     NaN
dtype: float64


a    10.0
b    20.0
c    30.0
d     NaN
e     NaN
dtype: float64

In [69]:
np.isnan(new_x)

a    False
b    False
c    False
d     True
e     True
dtype: bool

In [71]:
pd.isnull(new_x)

a    False
b    False
c    False
d     True
e     True
dtype: bool

In [73]:
data = [['a', 10], ['b', 20], ['c', 30]]
data

[['a', 10], ['b', 20], ['c', 30]]

In [77]:
df = pd.DataFrame(data, columns=['Name', 'Score'])
df

Name  Score
0    a     10
1    b     20
2    c     30

In [79]:
user_details = pd.read_csv('user_details.csv')
user_details

Title  firstName      lastName  gender                          email
0  Honorable   Alasdair        Beeckx    Male                abeeckx0@un.org
1         Dr    Saunder       Murname    Male              smurname1@ftc.gov
2  Honorable    Julissa      Spriddle  Female  jspriddle2@chicagotribune.com
3        Rev  Bernadene          Peak  Female                 bpeak3@fc2.com
4        Mrs       Cass  Bernardeschi    Male  cbernardeschi4@technorati.com
5  Honorable       Aggi        Lipson  Female               alipson5@ucoz.ru
6         Ms    Trescha        Damato  Female           tdamato6@skyrock.com
7         Dr        Dav        Headon    Male               dheadon7@ted.com
8  Honorable    Nealson       Janeway    Male               njaneway8@360.cn
9        Mrs      Laney        Trobey  Female        ltrobey9@eventbrite.com

In [83]:
user_details['Title']

0    Honorable
1           Dr
2    Honorable
3          Rev
4          Mrs
5    Honorable
6           Ms
7           Dr
8    Honorable
9          Mrs
Name: Title, dtype: object

In [85]:
user_details.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [94]:
user_details.iloc[1,4]

'smurname1@ftc.gov'

In [ ]:
sn